### ISSUE TITLE
Still generating api_version 3?

### ISSUE THREAD

**Issue by tdavis** [tenntenn/gae-go-testing#1]
Sorry to bother you, but I found this updated gae-go-testing library and have been trying to use it. Unfortunately, no matter what I do the app.yaml that is generated continues to have `api_version 3` in it! Do you have any idea why this might be?

**Comment by tenntenn** [comment]
You mean that this library works as 'api_version 3' yet on your computer? But I already fixed api_version to 'go1'. And I just fixed to enable each user to change api_version free.

**Comment by tdavis** [comment]
Oh, nice. I finally tracked down a `appenginetesting.a` file that was causing all the trouble :-/
