### ISSUE TITLE
How do I get this running?

### ISSUE THREAD

**Issue by tylerstillwater** [tenntenn/gae-go-testing#2]
Greetings! I am trying to get gae-go-testing working, but I have been unsuccessful so far.

My environment is as follows:

GAE is installed in:  $HOME/AppEngine/google_appengine

I use this bash function to setup my GAE environment when developing GAE apps:

```
function setup_appengine(){
  export APPENGINE_SDK="$HOME/AppEngine/google_appengine"
  export PATH="$APPENGINE_SDK":"$PATH"
}
```

After running that function, my go env is:

```
GOROOT="/Users/tylerb/AppEngine/google_appengine/goroot"
GOBIN=""
GOARCH="amd64"
GOCHAR="6"
GOOS="darwin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOTOOLDIR="/Users/tylerb/AppEngine/google_appengine/goroot/pkg/tool/darwin_amd64"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread -fno-common"
CGO_ENABLED="1"
```

echo $APPENGINE_SDK shows:

```
/Users/tylerb/AppEngine/google_appengine
```

When I attempt to run the python installation script, it fails with this error:

```
Traceback (most recent call last):
  File "<stdin>", line 55, in <module>
  File "<stdin>", line 49, in main
OSError: [Errno 13] Permission denied: '/usr/local/go/src/pkg/appengine'
```

I don't even have a /usr/local/go/src/pkg/appengine file or folder. What is wrong? How do I fix this?

Thanks!! :)

-Tyler

**Comment by mzimmerman** [comment]
Don't run the python installation script.  Follow the README of https://github.com/icub3d/appenginetesting
