### ISSUE TITLE
Call() has wrong signature for 1.7.1

### ISSUE THREAD

**Issue by SlothNinja** [tenntenn/gae-go-testing#3]
I believe the signature for Call changed in 1.7.1.  I'm receiving the error:
    have Call(string, string, interface {}, interface {}, *appengine_internal.CallOptions) error
        want Call(string, string, proto.Message, proto.Message, *appengine_internal.CallOptions) error

Looking at the code, it appears Call has not been updated for 1.7.1.

**Comment by tenntenn** [comment]
I fixed signature of Call.
